---
# tasks file for k8s

- name: Disabled swap
  ansible.builtin.shell:
    cmd: swapoff -a

- name: Add kubernets repository
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root

- name: install kubernetes packages
  ansible.builtin.yum:
    name:
    - kubelet
    - kubeadm
    - kubectl
    state: present

- name: sudo systemctl enable --now kubelet
  ansible.builtin.systemd_service:
    state: started
    name: kubelet
    # enabled: true

- name: cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
  template:
    src: k8s_modules_conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root


# cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
# overlay
# br_netfilter
# EOF

- name: modprobe overlay
  community.general.modprobe:
    name: overlay
    state: present

- name: modprobe br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

# modprobe overlay
# modprobe br_netfilter

# sysctl params required by setup, params persist across reboots

# - name: cat <<EOF | tee /etc/sysctl.d/k8s.conf
#   template:
#     src: k8s_modules_conf.j2
#     dest: /etc/sysctl.d/k8s.conf
#     owner: root
#     group: root
#     # mode: 0755

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

